version: '3.8'

services:
  hyperliquid-scraper:
    build: .
    container_name: hyperliquid-scraper
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Tokyo
      - USE_S3=true
      - S3_BUCKET_NAME=hl-data-scraper
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "com.example.description=Hyperliquid Data Scraper"
      - "com.example.service=hyperliquid-scraper"

volumes:
  data:
    driver: local
  logs:
    driver: local

networks:
  default:
    driver: bridge 